name: CI
on:
    push:
      branches:
        - master
    pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install nose
        run: |
          python -m pip install --upgrade pip
          pip install nose

      - name: Run tests
        run: nosetests -v
